name: 'Testing #1'
favicon: null
layout_spectrum: 0.99778
typography_spectrum: 0.31222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090e12'
    - '#8c8d91'
    - '#3c78af'
    - '#5dbafd'
    - '#86fdfe'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose:
  - name: stars
    item: null
    url: null
