name: 'Testing #1'
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5ac7f6'
    - '#000000'
    - '#00c004'
    - '#006d01'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: stars
    item: null
    url: null
